global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'netpulse-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add your network devices here
  # Example SNMP exporter configuration:
  # - job_name: 'snmp'
  #   static_configs:
  #     - targets:
  #       - 192.168.1.1  # Router
  #       - 192.168.1.2  # Switch
  #   metrics_path: /snmp
  #   params:
  #     module: [if_mib]
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: snmp-exporter:9116

  # Node exporter for system metrics
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']


